#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-json_pure
Version  : 1.8.3
Release  : 8
URL      : https://rubygems.org/downloads/json_pure-1.8.3.gem
Source0  : https://rubygems.org/downloads/json_pure-1.8.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : Ruby
BuildRequires : ruby
BuildRequires : rubygem-permutation
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-test-unit

%description
= JSON implementation for Ruby {<img src="https://secure.travis-ci.org/flori/json.png" />}[http://travis-ci.org/flori/json]

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n json_pure-1.8.3
gem spec %{SOURCE0} -l --ruby > rubygem-json_pure.gemspec

%build
gem build rubygem-json_pure.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
json_pure-1.8.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/json_pure-1.8.3
ruby -v -I.:lib:tests test*/test_*.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/json_pure-1.8.3.gem
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/.gitignore
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/.travis.yml
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/CHANGES
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/Gemfile
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/README-json-jruby.markdown
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/README.rdoc
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/TODO
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/VERSION
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/data/example.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/data/index.html
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/data/prototype.js
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/diagrams/.keep
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/ext/json/ext/fbuffer/fbuffer.h
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/ext/json/ext/generator/depend
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/ext/json/ext/generator/extconf.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/ext/json/ext/generator/generator.c
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/ext/json/ext/generator/generator.h
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/ext/json/ext/parser/depend
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/ext/json/ext/parser/extconf.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/ext/json/ext/parser/parser.c
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/ext/json/ext/parser/parser.h
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/ext/json/ext/parser/parser.rl
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/ext/json/extconf.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/install.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/java/src/json/ext/ByteListTranscoder.java
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/java/src/json/ext/Generator.java
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/java/src/json/ext/GeneratorMethods.java
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/java/src/json/ext/GeneratorService.java
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/java/src/json/ext/GeneratorState.java
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/java/src/json/ext/OptionsReader.java
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/java/src/json/ext/Parser.java
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/java/src/json/ext/Parser.rl
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/java/src/json/ext/ParserService.java
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/java/src/json/ext/RuntimeInfo.java
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/java/src/json/ext/StringDecoder.java
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/java/src/json/ext/StringEncoder.java
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/java/src/json/ext/Utils.java
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/json-java.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/json.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/json_pure.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/lib/json.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/lib/json/add/bigdecimal.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/lib/json/add/complex.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/lib/json/add/core.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/lib/json/add/date.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/lib/json/add/date_time.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/lib/json/add/exception.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/lib/json/add/ostruct.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/lib/json/add/range.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/lib/json/add/rational.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/lib/json/add/regexp.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/lib/json/add/struct.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/lib/json/add/symbol.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/lib/json/add/time.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/lib/json/common.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/lib/json/ext.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/lib/json/ext/.keep
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/lib/json/generic_object.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/lib/json/pure.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/lib/json/pure/generator.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/lib/json/pure/parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/lib/json/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/fail1.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/fail10.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/fail11.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/fail12.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/fail13.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/fail14.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/fail18.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/fail19.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/fail2.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/fail20.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/fail21.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/fail22.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/fail23.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/fail24.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/fail25.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/fail27.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/fail28.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/fail3.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/fail4.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/fail5.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/fail6.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/fail7.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/fail8.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/fail9.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/pass1.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/pass15.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/pass16.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/pass17.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/pass2.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/pass26.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/fixtures/pass3.json
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/setup_variant.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/test_json.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/test_json_addition.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/test_json_encoding.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/test_json_fixtures.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/test_json_generate.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/test_json_generic_object.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/test_json_string_matching.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tests/test_json_unicode.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tools/fuzz.rb
/usr/lib64/ruby/gems/2.3.0/gems/json_pure-1.8.3/tools/server.rb
/usr/lib64/ruby/gems/2.3.0/specifications/json_pure-1.8.3.gemspec
