#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-json_pure
Version  : 1.8.3
Release  : 6
URL      : https://rubygems.org/downloads/json_pure-1.8.3.gem
Source0  : https://rubygems.org/downloads/json_pure-1.8.3.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : Ruby
BuildRequires : ruby
BuildRequires : rubygem-permutation
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-test-unit

%description
= JSON implementation for Ruby {<img src="https://secure.travis-ci.org/flori/json.png" />}[http://travis-ci.org/flori/json]

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n json_pure-1.8.3
gem spec %{SOURCE0} -l --ruby > rubygem-json_pure.gemspec

%build
gem build rubygem-json_pure.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
json_pure-1.8.3.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
pushd %{buildroot}%{gem_dir}/gems/json_pure-1.8.3
ruby -v -I.:lib:tests test*/test_*.rb
popd


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/json_pure-1.8.3.gem
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/BigDecimal/as_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/BigDecimal/cdesc-BigDecimal.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/BigDecimal/json_create-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/BigDecimal/to_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Class/cdesc-Class.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Class/json_creatable%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Complex/as_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Complex/cdesc-Complex.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Complex/json_create-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Complex/to_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Date/as_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Date/cdesc-Date.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Date/json_create-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Date/to_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/DateTime/as_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/DateTime/cdesc-DateTime.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/DateTime/json_create-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/DateTime/to_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Exception/as_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Exception/cdesc-Exception.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Exception/json_create-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Exception/to_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/%5b%5d-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/CircularDatastructure/cdesc-CircularDatastructure.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Ext/cdesc-Ext.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/GeneratorError/cdesc-GeneratorError.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/GenericObject/%5b%5d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/GenericObject/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/GenericObject/%7c-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/GenericObject/as_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/GenericObject/cdesc-GenericObject.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/GenericObject/dump-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/GenericObject/from_hash-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/GenericObject/json_creatable%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/GenericObject/json_creatable-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/GenericObject/json_create-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/GenericObject/load-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/GenericObject/to_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/GenericObject/to_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/JSONError/cdesc-JSONError.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/JSONError/wrap-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/MissingUnicodeSupport/cdesc-MissingUnicodeSupport.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/NestingError/cdesc-NestingError.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/ParserError/cdesc-ParserError.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/GeneratorMethods/Array/cdesc-Array.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/GeneratorMethods/Array/json_transform-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/GeneratorMethods/Array/to_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/GeneratorMethods/FalseClass/cdesc-FalseClass.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/GeneratorMethods/FalseClass/to_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/GeneratorMethods/Float/cdesc-Float.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/GeneratorMethods/Float/to_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/GeneratorMethods/Hash/cdesc-Hash.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/GeneratorMethods/Hash/json_shift-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/GeneratorMethods/Hash/json_transform-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/GeneratorMethods/Hash/to_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/GeneratorMethods/Integer/cdesc-Integer.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/GeneratorMethods/Integer/to_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/GeneratorMethods/NilClass/cdesc-NilClass.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/GeneratorMethods/NilClass/to_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/GeneratorMethods/Object/cdesc-Object.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/GeneratorMethods/Object/to_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/GeneratorMethods/String/Extend/cdesc-Extend.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/GeneratorMethods/String/Extend/json_create-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/GeneratorMethods/String/cdesc-String.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/GeneratorMethods/String/included-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/GeneratorMethods/String/to_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/GeneratorMethods/String/to_json_raw-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/GeneratorMethods/String/to_json_raw_object-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/GeneratorMethods/TrueClass/cdesc-TrueClass.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/GeneratorMethods/TrueClass/to_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/GeneratorMethods/cdesc-GeneratorMethods.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/State/%5b%5d%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/State/%5b%5d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/State/allow_nan%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/State/array_nl-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/State/ascii_only%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/State/cdesc-State.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/State/check_circular%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/State/configure-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/State/depth-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/State/from_state-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/State/generate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/State/indent-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/State/max_nesting-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/State/merge-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/State/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/State/object_nl-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/State/quirks_mode%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/State/quirks_mode-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/State/space-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/State/space_before-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/State/to_h-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/State/to_hash-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Generator/cdesc-Generator.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Parser/Encoding/cdesc-Encoding.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Parser/cdesc-Parser.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Parser/convert_encoding-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Parser/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Parser/parse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Parser/parse_array-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Parser/parse_object-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Parser/parse_string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Parser/parse_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Parser/quirks_mode%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/Parser/reset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/Pure/cdesc-Pure.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/UnparserError/cdesc-UnparserError.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/cdesc-JSON.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/const_defined_in%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/create_id-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/dump-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/dump_default_options-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/fast_generate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/generate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/generator-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/iconv-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/load-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/load_default_options-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/parse%21-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/parse-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/parser-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/pretty_generate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/recurse_proc-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/restore-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/restore-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/state-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/valid_utf8%3f-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/JSON/valid_utf8%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Kernel/JSON-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Kernel/cdesc-Kernel.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Kernel/j-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Kernel/jj-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/OpenStruct/as_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/OpenStruct/cdesc-OpenStruct.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/OpenStruct/json_create-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/OpenStruct/to_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Range/as_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Range/cdesc-Range.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Range/json_create-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Range/to_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Rational/as_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Rational/cdesc-Rational.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Rational/json_create-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Rational/to_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Regexp/as_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Regexp/cdesc-Regexp.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Regexp/json_create-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Regexp/to_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Struct/as_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Struct/cdesc-Struct.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Struct/json_create-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Struct/to_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Symbol/as_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Symbol/cdesc-Symbol.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Symbol/json_create-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Symbol/to_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Time/as_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Time/cdesc-Time.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Time/json_create-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/Time/to_json-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/doc/json_pure-1.8.3/ri/page-README_rdoc.ri
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/.gitignore
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/.travis.yml
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/CHANGES
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/Gemfile
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/README-json-jruby.markdown
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/README.rdoc
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/TODO
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/VERSION
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/data/example.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/data/index.html
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/data/prototype.js
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/diagrams/.keep
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/ext/json/ext/fbuffer/fbuffer.h
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/ext/json/ext/generator/depend
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/ext/json/ext/generator/extconf.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/ext/json/ext/generator/generator.c
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/ext/json/ext/generator/generator.h
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/ext/json/ext/parser/depend
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/ext/json/ext/parser/extconf.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/ext/json/ext/parser/parser.c
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/ext/json/ext/parser/parser.h
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/ext/json/ext/parser/parser.rl
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/ext/json/extconf.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/install.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/java/src/json/ext/ByteListTranscoder.java
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/java/src/json/ext/Generator.java
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/java/src/json/ext/GeneratorMethods.java
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/java/src/json/ext/GeneratorService.java
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/java/src/json/ext/GeneratorState.java
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/java/src/json/ext/OptionsReader.java
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/java/src/json/ext/Parser.java
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/java/src/json/ext/Parser.rl
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/java/src/json/ext/ParserService.java
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/java/src/json/ext/RuntimeInfo.java
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/java/src/json/ext/StringDecoder.java
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/java/src/json/ext/StringEncoder.java
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/java/src/json/ext/Utils.java
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/json-java.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/json.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/json_pure.gemspec
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/add/bigdecimal.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/add/complex.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/add/core.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/add/date.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/add/date_time.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/add/exception.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/add/ostruct.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/add/range.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/add/rational.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/add/regexp.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/add/struct.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/add/symbol.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/add/time.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/common.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/ext.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/ext/.keep
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/generic_object.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/pure.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/pure/generator.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/pure/parser.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/lib/json/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/fail1.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/fail10.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/fail11.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/fail12.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/fail13.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/fail14.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/fail18.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/fail19.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/fail2.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/fail20.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/fail21.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/fail22.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/fail23.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/fail24.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/fail25.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/fail27.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/fail28.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/fail3.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/fail4.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/fail5.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/fail6.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/fail7.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/fail8.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/fail9.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/pass1.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/pass15.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/pass16.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/pass17.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/pass2.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/pass26.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/fixtures/pass3.json
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/setup_variant.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/test_json.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/test_json_addition.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/test_json_encoding.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/test_json_fixtures.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/test_json_generate.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/test_json_generic_object.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/test_json_string_matching.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tests/test_json_unicode.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tools/fuzz.rb
/usr/lib64/ruby/gems/2.2.0/gems/json_pure-1.8.3/tools/server.rb
/usr/lib64/ruby/gems/2.2.0/specifications/json_pure-1.8.3.gemspec
